spring:
  application:
    name: uber
  data:
    mongodb:
      # Use this clean format. The database name is explicitly set below.
      uri: mongodb+srv://tanishq2127tanishq_db_user:JdQgIg6fT177FXtD@clusteruber.uizk4gn.mongodb.net/?retryWrites=true&w=majority
      database: Uber_Tanishq
      auto-index-creation: true

# Custom properties for JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day